export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss', '@pinia/nuxt'],
  css: [
    'maplibre-gl/dist/maplibre-gl.css',
    '~/assets/css/main.css',
  ],
  app: {
    head: {
      title: 'Atlas Urabá — Bienestar Humano Territorial',
      htmlAttrs: { lang: 'es' },
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Índice de bienestar humano territorial por manzana para Urabá, Antioquia, Colombia. 7,028 manzanas · 8 municipios · 10 indicadores.' },
        { property: 'og:title', content: 'Atlas Urabá — Bienestar Humano Territorial' },
        { property: 'og:description', content: 'Plataforma interactiva de indicadores de bienestar por manzana para Urabá, Antioquia.' },
        { property: 'og:type', content: 'website' },
        { property: 'og:url', content: 'https://uraba.tensor.lat' },
        { property: 'og:image', content: 'https://uraba.tensor.lat/og-image.png' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:image:alt', content: 'Atlas Urabá — Mapa de bienestar humano territorial' },
        { property: 'og:locale', content: 'es_CO' },
        { property: 'og:site_name', content: 'Atlas Urabá' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:site', content: '@tensorlat' },
        { name: 'twitter:title', content: 'Atlas Urabá — Bienestar Humano Territorial' },
        { name: 'twitter:description', content: 'Plataforma interactiva de indicadores de bienestar por manzana para Urabá, Antioquia.' },
        { name: 'twitter:image', content: 'https://uraba.tensor.lat/og-image.png' },
        { name: 'twitter:image:alt', content: 'Atlas Urabá — Mapa de bienestar humano territorial' },
        { name: 'robots', content: 'index, follow' },
        { name: 'theme-color', content: '#0D1117' },
      ],
      link: [
        { rel: 'canonical', href: 'https://uraba.tensor.lat' },
      ],
    },
  },
  vite: {
    optimizeDeps: { include: ['maplibre-gl', 'pmtiles'] },
  },
  tailwindcss: { exposeConfig: true },
})
